CREATE TABLE `supermarket_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_no` VARCHAR(24) NOT NULL,
  `supermarket_name` VARCHAR(80) NOT NULL,
  `staff_id` INT NOT NULL,
  `staff_name` VARCHAR(40) NOT NULL,
  `total_amount` DECIMAL(10, 2) NOT NULL,
  `total_cost` DECIMAL(10, 2) NOT NULL,
  `total_commission` DECIMAL(10, 2) NOT NULL,
  `total_profit` DECIMAL(10, 2) NOT NULL,
  `status` ENUM('active', 'cancelled') NOT NULL DEFAULT 'active',
  `cancelled_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `supermarket_orders_order_no_key` (`order_no`),
  KEY `supermarket_orders_created_at_idx` (`created_at`),
  KEY `supermarket_orders_supermarket_name_idx` (`supermarket_name`),
  KEY `supermarket_orders_status_idx` (`status`),
  KEY `supermarket_orders_staff_id_idx` (`staff_id`),
  CONSTRAINT `supermarket_orders_staff_id_fkey` FOREIGN KEY (`staff_id`) REFERENCES `staff_users` (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `supermarket_order_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `type` ENUM('own', 'purchase') NOT NULL,
  `goods_id` INT NULL,
  `goods_name` VARCHAR(50) NOT NULL,
  `unit_type` ENUM('weight', 'qty') NOT NULL,
  `quantity` DECIMAL(10, 2) NOT NULL,
  `weight` DECIMAL(10, 2) NULL,
  `price` DECIMAL(10, 2) NOT NULL,
  `commission` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `cost_price` DECIMAL(10, 2) NOT NULL,
  `subtotal` DECIMAL(10, 2) NOT NULL,
  `cost_amount` DECIMAL(10, 2) NOT NULL,
  `profit` DECIMAL(10, 2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `supermarket_order_items_order_id_idx` (`order_id`),
  KEY `supermarket_order_items_goods_id_idx` (`goods_id`),
  CONSTRAINT `supermarket_order_items_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `supermarket_orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `supermarket_order_items_goods_id_fkey` FOREIGN KEY (`goods_id`) REFERENCES `goods` (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
