CREATE TABLE `retail_products` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(80) NOT NULL,
  `description` varchar(200) DEFAULT NULL,
  `category` enum('special','imported','domestic','gift','dry') NOT NULL,
  `source_type` enum('stock','consignment') NOT NULL,
  `goods_id` int DEFAULT NULL,
  `unit_type` enum('weight','qty') NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `cost_price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `commission` decimal(10,2) NOT NULL DEFAULT 0.00,
  `image_url` varchar(500) DEFAULT NULL,
  `sort_order` int NOT NULL DEFAULT 0,
  `enabled` tinyint(1) NOT NULL DEFAULT 1,
  `staff_id` int NOT NULL,
  `staff_name` varchar(40) NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `retail_products_category_sort_order_idx` (`category`, `sort_order`),
  KEY `retail_products_enabled_idx` (`enabled`),
  KEY `retail_products_goods_id_idx` (`goods_id`),
  KEY `retail_products_staff_id_idx` (`staff_id`),
  CONSTRAINT `retail_products_goods_id_fkey` FOREIGN KEY (`goods_id`) REFERENCES `goods` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `retail_products_staff_id_fkey` FOREIGN KEY (`staff_id`) REFERENCES `staff_users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `retail_orders` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_no` varchar(24) NOT NULL,
  `customer_name` varchar(80) NOT NULL,
  `customer_phone` varchar(40) DEFAULT NULL,
  `remark` varchar(300) DEFAULT NULL,
  `staff_id` int NOT NULL,
  `staff_name` varchar(40) NOT NULL,
  `total_amount` decimal(10,2) NOT NULL,
  `total_cost` decimal(10,2) NOT NULL DEFAULT 0.00,
  `total_profit` decimal(10,2) NOT NULL DEFAULT 0.00,
  `total_commission` decimal(10,2) NOT NULL,
  `status` enum('unpaid','paid') NOT NULL DEFAULT 'unpaid',
  `paid_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `retail_orders_order_no_key` (`order_no`),
  KEY `retail_orders_created_at_idx` (`created_at`),
  KEY `retail_orders_customer_name_idx` (`customer_name`),
  KEY `retail_orders_status_idx` (`status`),
  KEY `retail_orders_staff_id_idx` (`staff_id`),
  CONSTRAINT `retail_orders_staff_id_fkey` FOREIGN KEY (`staff_id`) REFERENCES `staff_users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `retail_order_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `product_id` int DEFAULT NULL,
  `source_type` enum('stock','consignment') NOT NULL,
  `goods_id` int DEFAULT NULL,
  `goods_name` varchar(80) NOT NULL,
  `category` enum('special','imported','domestic','gift','dry') NOT NULL,
  `unit_type` enum('weight','qty') NOT NULL,
  `quantity` decimal(10,2) NOT NULL,
  `weight` decimal(10,2) DEFAULT NULL,
  `price` decimal(10,2) NOT NULL,
  `cost_price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `cost_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `profit` decimal(10,2) NOT NULL DEFAULT 0.00,
  `commission` decimal(10,2) NOT NULL DEFAULT 0.00,
  `subtotal` decimal(10,2) NOT NULL,
  `image_url` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `retail_order_items_order_id_idx` (`order_id`),
  KEY `retail_order_items_product_id_idx` (`product_id`),
  KEY `retail_order_items_goods_id_idx` (`goods_id`),
  CONSTRAINT `retail_order_items_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `retail_orders` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `retail_order_items_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `retail_products` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
