CREATE TABLE `print_records` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('order', 'customer_debt') NOT NULL,
  `status` ENUM('success', 'failed') NOT NULL,
  `staff_id` INT NOT NULL,
  `staff_name` VARCHAR(40) NOT NULL,
  `order_id` INT NULL,
  `order_no` VARCHAR(24) NULL,
  `customer_id` INT NULL,
  `customer_name` VARCHAR(50) NULL,
  `printer_sn` VARCHAR(80) NULL,
  `content` TEXT NOT NULL,
  `response` JSON NULL,
  `error_message` VARCHAR(500) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `print_records_created_at_idx` (`created_at`),
  KEY `print_records_type_status_idx` (`type`, `status`),
  KEY `print_records_staff_id_idx` (`staff_id`),
  KEY `print_records_order_id_idx` (`order_id`),
  KEY `print_records_order_no_idx` (`order_no`),
  KEY `print_records_customer_id_idx` (`customer_id`),
  CONSTRAINT `print_records_staff_id_fkey` FOREIGN KEY (`staff_id`) REFERENCES `staff_users` (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
