CREATE TABLE `suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `partial_payment` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `total_debt` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `suppliers_name_key` (`name`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `supplier_entries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `entry_no` VARCHAR(24) NOT NULL,
  `supplier_id` INT NOT NULL,
  `supplier_name` VARCHAR(80) NOT NULL,
  `staff_id` INT NOT NULL,
  `staff_name` VARCHAR(40) NOT NULL,
  `goods_id` INT NULL,
  `goods_name` VARCHAR(50) NOT NULL,
  `unit_type` ENUM('weight', 'qty') NOT NULL,
  `quantity` DECIMAL(10, 2) NOT NULL,
  `weight` DECIMAL(10, 2) NULL,
  `total_amount` DECIMAL(10, 2) NOT NULL,
  `total_commission` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `cost_price` DECIMAL(10, 2) NOT NULL,
  `commission` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `sale_price` DECIMAL(10, 2) NOT NULL,
  `stock_mode` ENUM('record_only', 'auto_stocked') NOT NULL DEFAULT 'record_only',
  `status` ENUM('unpaid', 'paid') NOT NULL DEFAULT 'unpaid',
  `paid_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `supplier_entries_entry_no_key` (`entry_no`),
  KEY `supplier_entries_created_at_idx` (`created_at`),
  KEY `supplier_entries_supplier_id_idx` (`supplier_id`),
  KEY `supplier_entries_supplier_name_idx` (`supplier_name`),
  KEY `supplier_entries_status_idx` (`status`),
  KEY `supplier_entries_goods_id_idx` (`goods_id`),
  KEY `supplier_entries_staff_id_fkey` (`staff_id`),
  CONSTRAINT `supplier_entries_supplier_id_fkey` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`),
  CONSTRAINT `supplier_entries_staff_id_fkey` FOREIGN KEY (`staff_id`) REFERENCES `staff_users` (`id`),
  CONSTRAINT `supplier_entries_goods_id_fkey` FOREIGN KEY (`goods_id`) REFERENCES `goods` (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
